# Generated by Django 3.2.6 on 2021-09-07 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SLB_App', '0002_recipe_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='url',
        ),
    ]
