# Generated by Django 3.2.6 on 2021-09-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SLB_App', '0005_auto_20210908_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='SLB_App/static/apple.jpg', upload_to=''),
        ),
    ]
