# Generated by Django 3.2.6 on 2021-09-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SLB_App', '0006_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.FilePathField(path='/'),
        ),
    ]
