# Generated by Django 3.2.6 on 2021-09-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SLB_App', '0008_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='contents',
            field=models.JSONField(default=list),
        ),
    ]
