# Generated by Django 3.2.6 on 2021-09-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SLB_App', '0009_alter_basket_contents'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'ordering': ('recipes',)},
        ),
        migrations.AddField(
            model_name='basket',
            name='recipes',
            field=models.JSONField(default=list),
        ),
    ]
