# Generated by Django 3.2.6 on 2021-09-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SLB_App', '0011_alter_basket_recipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='recipes',
            field=models.JSONField(default=list),
        ),
    ]
