# Generated by Django 3.2.6 on 2021-09-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SLB_App', '0013_alter_basket_recipes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={},
        ),
        migrations.AlterField(
            model_name='basket',
            name='recipes',
            field=models.JSONField(default=list),
        ),
    ]
