# Generated by Django 3.2.6 on 2021-09-21 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SLB_App', '0015_basket_basketnum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='basketNum',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='recipes',
        ),
    ]
