# Generated by Django 3.2.6 on 2021-09-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SLB_App', '0016_auto_20210921_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='recipes',
            field=models.JSONField(default=list),
        ),
    ]
