# Generated by Django 3.2.6 on 2021-09-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SLB_App', '0017_basket_recipes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='inCart',
            field=models.BooleanField(default=False),
        ),
    ]
