# Generated by Django 3.2.6 on 2021-09-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SLB_App', '0018_recipe_incart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='contents',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='basket',
            name='recipes',
            field=models.JSONField(default=dict),
        ),
    ]
